apiVersion: batch/v1
kind: Job
metadata:
  name: pre-pync-job
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: pre-pync-job
          image: alpine:latest
          command: ["sleep", "10"]
#          command: ["exit", "1"]
      restartPolicy: Never
  backoffLimit: 0