apiVersion: batch/v1
kind: Job
metadata:
  name: clean-up-init-timelist
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: launch-time
          image: redis
          command: ['bash', '-c', 'printf "DEL init_time" | redis-cli -h demo-redis -p 6379']
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: reset-init-incr
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
        - name: incr
          image: redis
          command: [ 'bash', '-c', 'printf "SET init_incr 0" | redis-cli -h demo-redis -p 6379' ]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis
          name: redis
          ports:
            - name: client
              containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: client # named port
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 3